#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DadosFinanceiros
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Represa02")]
	public partial class RepresaContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAtendente(Atendente instance);
    partial void UpdateAtendente(Atendente instance);
    partial void DeleteAtendente(Atendente instance);
    partial void InsertParcela(Parcela instance);
    partial void UpdateParcela(Parcela instance);
    partial void DeleteParcela(Parcela instance);
    partial void InsertBanco(Banco instance);
    partial void UpdateBanco(Banco instance);
    partial void DeleteBanco(Banco instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertEmprestimo(Emprestimo instance);
    partial void UpdateEmprestimo(Emprestimo instance);
    partial void DeleteEmprestimo(Emprestimo instance);
    partial void InsertFPagamento(FPagamento instance);
    partial void UpdateFPagamento(FPagamento instance);
    partial void DeleteFPagamento(FPagamento instance);
    #endregion
		
		public RepresaContextDataContext() : 
				base(global::DadosFinanceiros.Properties.Settings.Default.Represa02ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RepresaContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RepresaContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RepresaContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RepresaContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Atendente> Atendente
		{
			get
			{
				return this.GetTable<Atendente>();
			}
		}
		
		public System.Data.Linq.Table<Parcela> Parcela
		{
			get
			{
				return this.GetTable<Parcela>();
			}
		}
		
		public System.Data.Linq.Table<Banco> Banco
		{
			get
			{
				return this.GetTable<Banco>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Emprestimo> Emprestimo
		{
			get
			{
				return this.GetTable<Emprestimo>();
			}
		}
		
		public System.Data.Linq.Table<FPagamento> FPagamento
		{
			get
			{
				return this.GetTable<FPagamento>();
			}
		}
		
		public System.Data.Linq.Table<View_AplicacaoCliente> View_AplicacaoCliente
		{
			get
			{
				return this.GetTable<View_AplicacaoCliente>();
			}
		}
		
		public System.Data.Linq.Table<View_Refinanciar> View_Refinanciar
		{
			get
			{
				return this.GetTable<View_Refinanciar>();
			}
		}
		
		public System.Data.Linq.Table<View_ClienteEmprestimo> View_ClienteEmprestimo
		{
			get
			{
				return this.GetTable<View_ClienteEmprestimo>();
			}
		}
		
		public System.Data.Linq.Table<View_Recebimento> View_Recebimento
		{
			get
			{
				return this.GetTable<View_Recebimento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Atendente")]
	public partial class Atendente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idAtendende;
		
		private string _nomeAtendente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidAtendendeChanging(int value);
    partial void OnidAtendendeChanged();
    partial void OnnomeAtendenteChanging(string value);
    partial void OnnomeAtendenteChanged();
    #endregion
		
		public Atendente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAtendende", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idAtendende
		{
			get
			{
				return this._idAtendende;
			}
			set
			{
				if ((this._idAtendende != value))
				{
					this.OnidAtendendeChanging(value);
					this.SendPropertyChanging();
					this._idAtendende = value;
					this.SendPropertyChanged("idAtendende");
					this.OnidAtendendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeAtendente", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomeAtendente
		{
			get
			{
				return this._nomeAtendente;
			}
			set
			{
				if ((this._nomeAtendente != value))
				{
					this.OnnomeAtendenteChanging(value);
					this.SendPropertyChanging();
					this._nomeAtendente = value;
					this.SendPropertyChanged("nomeAtendente");
					this.OnnomeAtendenteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parcela")]
	public partial class Parcela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idParcela;
		
		private int _idEmprestimo;
		
		private System.DateTime _vencimento;
		
		private decimal _valorParcela;
		
		private bool _paga;
		
		private System.Nullable<System.DateTime> _novadata;
		
		private System.Nullable<short> _taxaParcela;
		
		private System.Nullable<decimal> _novovalor;
		
		private EntityRef<Emprestimo> _Emprestimo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidParcelaChanging(int value);
    partial void OnidParcelaChanged();
    partial void OnidEmprestimoChanging(int value);
    partial void OnidEmprestimoChanged();
    partial void OnvencimentoChanging(System.DateTime value);
    partial void OnvencimentoChanged();
    partial void OnvalorParcelaChanging(decimal value);
    partial void OnvalorParcelaChanged();
    partial void OnpagaChanging(bool value);
    partial void OnpagaChanged();
    partial void OnnovadataChanging(System.Nullable<System.DateTime> value);
    partial void OnnovadataChanged();
    partial void OntaxaParcelaChanging(System.Nullable<short> value);
    partial void OntaxaParcelaChanged();
    partial void OnnovovalorChanging(System.Nullable<decimal> value);
    partial void OnnovovalorChanged();
    #endregion
		
		public Parcela()
		{
			this._Emprestimo = default(EntityRef<Emprestimo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idParcela", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idParcela
		{
			get
			{
				return this._idParcela;
			}
			set
			{
				if ((this._idParcela != value))
				{
					this.OnidParcelaChanging(value);
					this.SendPropertyChanging();
					this._idParcela = value;
					this.SendPropertyChanged("idParcela");
					this.OnidParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmprestimo", DbType="Int NOT NULL")]
		public int idEmprestimo
		{
			get
			{
				return this._idEmprestimo;
			}
			set
			{
				if ((this._idEmprestimo != value))
				{
					if (this._Emprestimo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._idEmprestimo = value;
					this.SendPropertyChanged("idEmprestimo");
					this.OnidEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimento", DbType="Date NOT NULL")]
		public System.DateTime vencimento
		{
			get
			{
				return this._vencimento;
			}
			set
			{
				if ((this._vencimento != value))
				{
					this.OnvencimentoChanging(value);
					this.SendPropertyChanging();
					this._vencimento = value;
					this.SendPropertyChanged("vencimento");
					this.OnvencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorParcela", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorParcela
		{
			get
			{
				return this._valorParcela;
			}
			set
			{
				if ((this._valorParcela != value))
				{
					this.OnvalorParcelaChanging(value);
					this.SendPropertyChanging();
					this._valorParcela = value;
					this.SendPropertyChanged("valorParcela");
					this.OnvalorParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paga", DbType="Bit NOT NULL")]
		public bool paga
		{
			get
			{
				return this._paga;
			}
			set
			{
				if ((this._paga != value))
				{
					this.OnpagaChanging(value);
					this.SendPropertyChanging();
					this._paga = value;
					this.SendPropertyChanged("paga");
					this.OnpagaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_novadata", DbType="Date")]
		public System.Nullable<System.DateTime> novadata
		{
			get
			{
				return this._novadata;
			}
			set
			{
				if ((this._novadata != value))
				{
					this.OnnovadataChanging(value);
					this.SendPropertyChanging();
					this._novadata = value;
					this.SendPropertyChanged("novadata");
					this.OnnovadataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxaParcela", DbType="SmallInt")]
		public System.Nullable<short> taxaParcela
		{
			get
			{
				return this._taxaParcela;
			}
			set
			{
				if ((this._taxaParcela != value))
				{
					this.OntaxaParcelaChanging(value);
					this.SendPropertyChanging();
					this._taxaParcela = value;
					this.SendPropertyChanged("taxaParcela");
					this.OntaxaParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_novovalor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> novovalor
		{
			get
			{
				return this._novovalor;
			}
			set
			{
				if ((this._novovalor != value))
				{
					this.OnnovovalorChanging(value);
					this.SendPropertyChanging();
					this._novovalor = value;
					this.SendPropertyChanged("novovalor");
					this.OnnovovalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Emprestimo_Parcela", Storage="_Emprestimo", ThisKey="idEmprestimo", OtherKey="idEmprestimo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Emprestimo Emprestimo
		{
			get
			{
				return this._Emprestimo.Entity;
			}
			set
			{
				Emprestimo previousValue = this._Emprestimo.Entity;
				if (((previousValue != value) 
							|| (this._Emprestimo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Emprestimo.Entity = null;
						previousValue.Parcela.Remove(this);
					}
					this._Emprestimo.Entity = value;
					if ((value != null))
					{
						value.Parcela.Add(this);
						this._idEmprestimo = value.idEmprestimo;
					}
					else
					{
						this._idEmprestimo = default(int);
					}
					this.SendPropertyChanged("Emprestimo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Banco")]
	public partial class Banco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBanco;
		
		private string _nomeBanco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBancoChanging(int value);
    partial void OnidBancoChanged();
    partial void OnnomeBancoChanging(string value);
    partial void OnnomeBancoChanged();
    #endregion
		
		public Banco()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBanco", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBanco
		{
			get
			{
				return this._idBanco;
			}
			set
			{
				if ((this._idBanco != value))
				{
					this.OnidBancoChanging(value);
					this.SendPropertyChanging();
					this._idBanco = value;
					this.SendPropertyChanged("idBanco");
					this.OnidBancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeBanco", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomeBanco
		{
			get
			{
				return this._nomeBanco;
			}
			set
			{
				if ((this._nomeBanco != value))
				{
					this.OnnomeBancoChanging(value);
					this.SendPropertyChanging();
					this._nomeBanco = value;
					this.SendPropertyChanged("nomeBanco");
					this.OnnomeBancoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCliente;
		
		private string _codCliente;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private string _nomeCliente;
		
		private System.Nullable<System.DateTime> _dataNascimento;
		
		private string _cpf;
		
		private string _rg;
		
		private string _telResidencial;
		
		private string _telCelularzap;
		
		private string _telCelular2;
		
		private string _enderecoResidencial;
		
		private string _email;
		
		private string _facebook;
		
		private string _instagran;
		
		private string _empresa;
		
		private string _cargo;
		
		private System.Nullable<decimal> _salarioLiquido;
		
		private System.Nullable<System.DateTime> _dataEmpresa;
		
		private string _telComercial1;
		
		private string _telComercial2;
		
		private string _telComercial3;
		
		private string _enderecoEmpresarial;
		
		private string _referencia1;
		
		private string _referencia2;
		
		private string _referencia3;
		
		private string _observacao;
		
		private System.Nullable<bool> _statusCadastro;
		
		private EntitySet<Emprestimo> _Emprestimo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OncodClienteChanging(string value);
    partial void OncodClienteChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OnnomeClienteChanging(string value);
    partial void OnnomeClienteChanged();
    partial void OndataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OndataNascimentoChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    partial void OntelResidencialChanging(string value);
    partial void OntelResidencialChanged();
    partial void OntelCelularzapChanging(string value);
    partial void OntelCelularzapChanged();
    partial void OntelCelular2Changing(string value);
    partial void OntelCelular2Changed();
    partial void OnenderecoResidencialChanging(string value);
    partial void OnenderecoResidencialChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfacebookChanging(string value);
    partial void OnfacebookChanged();
    partial void OninstagranChanging(string value);
    partial void OninstagranChanged();
    partial void OnempresaChanging(string value);
    partial void OnempresaChanged();
    partial void OncargoChanging(string value);
    partial void OncargoChanged();
    partial void OnsalarioLiquidoChanging(System.Nullable<decimal> value);
    partial void OnsalarioLiquidoChanged();
    partial void OndataEmpresaChanging(System.Nullable<System.DateTime> value);
    partial void OndataEmpresaChanged();
    partial void OntelComercial1Changing(string value);
    partial void OntelComercial1Changed();
    partial void OntelComercial2Changing(string value);
    partial void OntelComercial2Changed();
    partial void OntelComercial3Changing(string value);
    partial void OntelComercial3Changed();
    partial void OnenderecoEmpresarialChanging(string value);
    partial void OnenderecoEmpresarialChanged();
    partial void Onreferencia1Changing(string value);
    partial void Onreferencia1Changed();
    partial void Onreferencia2Changing(string value);
    partial void Onreferencia2Changed();
    partial void Onreferencia3Changing(string value);
    partial void Onreferencia3Changed();
    partial void OnobservacaoChanging(string value);
    partial void OnobservacaoChanged();
    partial void OnstatusCadastroChanging(System.Nullable<bool> value);
    partial void OnstatusCadastroChanged();
    #endregion
		
		public Cliente()
		{
			this._Emprestimo = new EntitySet<Emprestimo>(new Action<Emprestimo>(this.attach_Emprestimo), new Action<Emprestimo>(this.detach_Emprestimo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this.OncodClienteChanging(value);
					this.SendPropertyChanging();
					this._codCliente = value;
					this.SendPropertyChanged("codCliente");
					this.OncodClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="Date")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCliente", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomeCliente
		{
			get
			{
				return this._nomeCliente;
			}
			set
			{
				if ((this._nomeCliente != value))
				{
					this.OnnomeClienteChanging(value);
					this.SendPropertyChanging();
					this._nomeCliente = value;
					this.SendPropertyChanged("nomeCliente");
					this.OnnomeClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataNascimento", DbType="Date")]
		public System.Nullable<System.DateTime> dataNascimento
		{
			get
			{
				return this._dataNascimento;
			}
			set
			{
				if ((this._dataNascimento != value))
				{
					this.OndataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._dataNascimento = value;
					this.SendPropertyChanged("dataNascimento");
					this.OndataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="NVarChar(15)")]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="NVarChar(20)")]
		public string rg
		{
			get
			{
				return this._rg;
			}
			set
			{
				if ((this._rg != value))
				{
					this.OnrgChanging(value);
					this.SendPropertyChanging();
					this._rg = value;
					this.SendPropertyChanged("rg");
					this.OnrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telResidencial", DbType="NVarChar(20)")]
		public string telResidencial
		{
			get
			{
				return this._telResidencial;
			}
			set
			{
				if ((this._telResidencial != value))
				{
					this.OntelResidencialChanging(value);
					this.SendPropertyChanging();
					this._telResidencial = value;
					this.SendPropertyChanged("telResidencial");
					this.OntelResidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telCelularzap", DbType="NVarChar(20)")]
		public string telCelularzap
		{
			get
			{
				return this._telCelularzap;
			}
			set
			{
				if ((this._telCelularzap != value))
				{
					this.OntelCelularzapChanging(value);
					this.SendPropertyChanging();
					this._telCelularzap = value;
					this.SendPropertyChanged("telCelularzap");
					this.OntelCelularzapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telCelular2", DbType="NVarChar(20)")]
		public string telCelular2
		{
			get
			{
				return this._telCelular2;
			}
			set
			{
				if ((this._telCelular2 != value))
				{
					this.OntelCelular2Changing(value);
					this.SendPropertyChanging();
					this._telCelular2 = value;
					this.SendPropertyChanged("telCelular2");
					this.OntelCelular2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enderecoResidencial", DbType="NVarChar(500)")]
		public string enderecoResidencial
		{
			get
			{
				return this._enderecoResidencial;
			}
			set
			{
				if ((this._enderecoResidencial != value))
				{
					this.OnenderecoResidencialChanging(value);
					this.SendPropertyChanging();
					this._enderecoResidencial = value;
					this.SendPropertyChanged("enderecoResidencial");
					this.OnenderecoResidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facebook", DbType="NVarChar(100)")]
		public string facebook
		{
			get
			{
				return this._facebook;
			}
			set
			{
				if ((this._facebook != value))
				{
					this.OnfacebookChanging(value);
					this.SendPropertyChanging();
					this._facebook = value;
					this.SendPropertyChanged("facebook");
					this.OnfacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instagran", DbType="NVarChar(100)")]
		public string instagran
		{
			get
			{
				return this._instagran;
			}
			set
			{
				if ((this._instagran != value))
				{
					this.OninstagranChanging(value);
					this.SendPropertyChanging();
					this._instagran = value;
					this.SendPropertyChanged("instagran");
					this.OninstagranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empresa", DbType="NVarChar(100)")]
		public string empresa
		{
			get
			{
				return this._empresa;
			}
			set
			{
				if ((this._empresa != value))
				{
					this.OnempresaChanging(value);
					this.SendPropertyChanging();
					this._empresa = value;
					this.SendPropertyChanged("empresa");
					this.OnempresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargo", DbType="NVarChar(100)")]
		public string cargo
		{
			get
			{
				return this._cargo;
			}
			set
			{
				if ((this._cargo != value))
				{
					this.OncargoChanging(value);
					this.SendPropertyChanging();
					this._cargo = value;
					this.SendPropertyChanged("cargo");
					this.OncargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salarioLiquido", DbType="Money")]
		public System.Nullable<decimal> salarioLiquido
		{
			get
			{
				return this._salarioLiquido;
			}
			set
			{
				if ((this._salarioLiquido != value))
				{
					this.OnsalarioLiquidoChanging(value);
					this.SendPropertyChanging();
					this._salarioLiquido = value;
					this.SendPropertyChanged("salarioLiquido");
					this.OnsalarioLiquidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataEmpresa", DbType="Date")]
		public System.Nullable<System.DateTime> dataEmpresa
		{
			get
			{
				return this._dataEmpresa;
			}
			set
			{
				if ((this._dataEmpresa != value))
				{
					this.OndataEmpresaChanging(value);
					this.SendPropertyChanging();
					this._dataEmpresa = value;
					this.SendPropertyChanged("dataEmpresa");
					this.OndataEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telComercial1", DbType="NVarChar(20)")]
		public string telComercial1
		{
			get
			{
				return this._telComercial1;
			}
			set
			{
				if ((this._telComercial1 != value))
				{
					this.OntelComercial1Changing(value);
					this.SendPropertyChanging();
					this._telComercial1 = value;
					this.SendPropertyChanged("telComercial1");
					this.OntelComercial1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telComercial2", DbType="NVarChar(20)")]
		public string telComercial2
		{
			get
			{
				return this._telComercial2;
			}
			set
			{
				if ((this._telComercial2 != value))
				{
					this.OntelComercial2Changing(value);
					this.SendPropertyChanging();
					this._telComercial2 = value;
					this.SendPropertyChanged("telComercial2");
					this.OntelComercial2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telComercial3", DbType="NVarChar(20)")]
		public string telComercial3
		{
			get
			{
				return this._telComercial3;
			}
			set
			{
				if ((this._telComercial3 != value))
				{
					this.OntelComercial3Changing(value);
					this.SendPropertyChanging();
					this._telComercial3 = value;
					this.SendPropertyChanged("telComercial3");
					this.OntelComercial3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enderecoEmpresarial", DbType="NVarChar(500)")]
		public string enderecoEmpresarial
		{
			get
			{
				return this._enderecoEmpresarial;
			}
			set
			{
				if ((this._enderecoEmpresarial != value))
				{
					this.OnenderecoEmpresarialChanging(value);
					this.SendPropertyChanging();
					this._enderecoEmpresarial = value;
					this.SendPropertyChanged("enderecoEmpresarial");
					this.OnenderecoEmpresarialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia1", DbType="NVarChar(200)")]
		public string referencia1
		{
			get
			{
				return this._referencia1;
			}
			set
			{
				if ((this._referencia1 != value))
				{
					this.Onreferencia1Changing(value);
					this.SendPropertyChanging();
					this._referencia1 = value;
					this.SendPropertyChanged("referencia1");
					this.Onreferencia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia2", DbType="NVarChar(200)")]
		public string referencia2
		{
			get
			{
				return this._referencia2;
			}
			set
			{
				if ((this._referencia2 != value))
				{
					this.Onreferencia2Changing(value);
					this.SendPropertyChanging();
					this._referencia2 = value;
					this.SendPropertyChanged("referencia2");
					this.Onreferencia2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia3", DbType="NVarChar(200)")]
		public string referencia3
		{
			get
			{
				return this._referencia3;
			}
			set
			{
				if ((this._referencia3 != value))
				{
					this.Onreferencia3Changing(value);
					this.SendPropertyChanging();
					this._referencia3 = value;
					this.SendPropertyChanged("referencia3");
					this.Onreferencia3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacao", DbType="NVarChar(800)")]
		public string observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				if ((this._observacao != value))
				{
					this.OnobservacaoChanging(value);
					this.SendPropertyChanging();
					this._observacao = value;
					this.SendPropertyChanged("observacao");
					this.OnobservacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusCadastro", DbType="Bit")]
		public System.Nullable<bool> statusCadastro
		{
			get
			{
				return this._statusCadastro;
			}
			set
			{
				if ((this._statusCadastro != value))
				{
					this.OnstatusCadastroChanging(value);
					this.SendPropertyChanging();
					this._statusCadastro = value;
					this.SendPropertyChanged("statusCadastro");
					this.OnstatusCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Emprestimo", Storage="_Emprestimo", ThisKey="idCliente", OtherKey="idCliente")]
		public EntitySet<Emprestimo> Emprestimo
		{
			get
			{
				return this._Emprestimo;
			}
			set
			{
				this._Emprestimo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Emprestimo(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Emprestimo(Emprestimo entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Emprestimo")]
	public partial class Emprestimo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmprestimo;
		
		private int _idCliente;
		
		private string _nomeAtendente;
		
		private System.Nullable<bool> _statusEmprestimo;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private decimal _valor;
		
		private short _taxa;
		
		private decimal _valorTotal;
		
		private short _qtdParcela;
		
		private decimal _valorParcela;
		
		private System.Nullable<System.DateTime> _primeiraParcela;
		
		private System.Nullable<System.DateTime> _ultimaParcela;
		
		private System.Nullable<int> _percentComissao;
		
		private System.Nullable<decimal> _valorComissao;
		
		private System.Nullable<bool> _refinanciamento;
		
		private System.Nullable<decimal> _complemento;
		
		private string _banco;
		
		private string _formaPagamento;
		
		private string _observacao;
		
		private EntitySet<Parcela> _Parcela;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmprestimoChanging(int value);
    partial void OnidEmprestimoChanged();
    partial void OnidClienteChanging(int value);
    partial void OnidClienteChanged();
    partial void OnnomeAtendenteChanging(string value);
    partial void OnnomeAtendenteChanged();
    partial void OnstatusEmprestimoChanging(System.Nullable<bool> value);
    partial void OnstatusEmprestimoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    partial void OntaxaChanging(short value);
    partial void OntaxaChanged();
    partial void OnvalorTotalChanging(decimal value);
    partial void OnvalorTotalChanged();
    partial void OnqtdParcelaChanging(short value);
    partial void OnqtdParcelaChanged();
    partial void OnvalorParcelaChanging(decimal value);
    partial void OnvalorParcelaChanged();
    partial void OnprimeiraParcelaChanging(System.Nullable<System.DateTime> value);
    partial void OnprimeiraParcelaChanged();
    partial void OnultimaParcelaChanging(System.Nullable<System.DateTime> value);
    partial void OnultimaParcelaChanged();
    partial void OnpercentComissaoChanging(System.Nullable<int> value);
    partial void OnpercentComissaoChanged();
    partial void OnvalorComissaoChanging(System.Nullable<decimal> value);
    partial void OnvalorComissaoChanged();
    partial void OnrefinanciamentoChanging(System.Nullable<bool> value);
    partial void OnrefinanciamentoChanged();
    partial void OncomplementoChanging(System.Nullable<decimal> value);
    partial void OncomplementoChanged();
    partial void OnbancoChanging(string value);
    partial void OnbancoChanged();
    partial void OnformaPagamentoChanging(string value);
    partial void OnformaPagamentoChanged();
    partial void OnobservacaoChanging(string value);
    partial void OnobservacaoChanged();
    #endregion
		
		public Emprestimo()
		{
			this._Parcela = new EntitySet<Parcela>(new Action<Parcela>(this.attach_Parcela), new Action<Parcela>(this.detach_Parcela));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmprestimo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmprestimo
		{
			get
			{
				return this._idEmprestimo;
			}
			set
			{
				if ((this._idEmprestimo != value))
				{
					this.OnidEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._idEmprestimo = value;
					this.SendPropertyChanged("idEmprestimo");
					this.OnidEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClienteChanging(value);
					this.SendPropertyChanging();
					this._idCliente = value;
					this.SendPropertyChanged("idCliente");
					this.OnidClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeAtendente", DbType="NVarChar(60)")]
		public string nomeAtendente
		{
			get
			{
				return this._nomeAtendente;
			}
			set
			{
				if ((this._nomeAtendente != value))
				{
					this.OnnomeAtendenteChanging(value);
					this.SendPropertyChanging();
					this._nomeAtendente = value;
					this.SendPropertyChanged("nomeAtendente");
					this.OnnomeAtendenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusEmprestimo", DbType="Bit")]
		public System.Nullable<bool> statusEmprestimo
		{
			get
			{
				return this._statusEmprestimo;
			}
			set
			{
				if ((this._statusEmprestimo != value))
				{
					this.OnstatusEmprestimoChanging(value);
					this.SendPropertyChanging();
					this._statusEmprestimo = value;
					this.SendPropertyChanged("statusEmprestimo");
					this.OnstatusEmprestimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="Date")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(18,0) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxa", DbType="SmallInt NOT NULL")]
		public short taxa
		{
			get
			{
				return this._taxa;
			}
			set
			{
				if ((this._taxa != value))
				{
					this.OntaxaChanging(value);
					this.SendPropertyChanging();
					this._taxa = value;
					this.SendPropertyChanged("taxa");
					this.OntaxaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorTotal", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorTotal
		{
			get
			{
				return this._valorTotal;
			}
			set
			{
				if ((this._valorTotal != value))
				{
					this.OnvalorTotalChanging(value);
					this.SendPropertyChanging();
					this._valorTotal = value;
					this.SendPropertyChanged("valorTotal");
					this.OnvalorTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdParcela", DbType="SmallInt NOT NULL")]
		public short qtdParcela
		{
			get
			{
				return this._qtdParcela;
			}
			set
			{
				if ((this._qtdParcela != value))
				{
					this.OnqtdParcelaChanging(value);
					this.SendPropertyChanging();
					this._qtdParcela = value;
					this.SendPropertyChanged("qtdParcela");
					this.OnqtdParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorParcela", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorParcela
		{
			get
			{
				return this._valorParcela;
			}
			set
			{
				if ((this._valorParcela != value))
				{
					this.OnvalorParcelaChanging(value);
					this.SendPropertyChanging();
					this._valorParcela = value;
					this.SendPropertyChanged("valorParcela");
					this.OnvalorParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primeiraParcela", DbType="Date")]
		public System.Nullable<System.DateTime> primeiraParcela
		{
			get
			{
				return this._primeiraParcela;
			}
			set
			{
				if ((this._primeiraParcela != value))
				{
					this.OnprimeiraParcelaChanging(value);
					this.SendPropertyChanging();
					this._primeiraParcela = value;
					this.SendPropertyChanged("primeiraParcela");
					this.OnprimeiraParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ultimaParcela", DbType="Date")]
		public System.Nullable<System.DateTime> ultimaParcela
		{
			get
			{
				return this._ultimaParcela;
			}
			set
			{
				if ((this._ultimaParcela != value))
				{
					this.OnultimaParcelaChanging(value);
					this.SendPropertyChanging();
					this._ultimaParcela = value;
					this.SendPropertyChanged("ultimaParcela");
					this.OnultimaParcelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentComissao", DbType="Int")]
		public System.Nullable<int> percentComissao
		{
			get
			{
				return this._percentComissao;
			}
			set
			{
				if ((this._percentComissao != value))
				{
					this.OnpercentComissaoChanging(value);
					this.SendPropertyChanging();
					this._percentComissao = value;
					this.SendPropertyChanged("percentComissao");
					this.OnpercentComissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorComissao", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> valorComissao
		{
			get
			{
				return this._valorComissao;
			}
			set
			{
				if ((this._valorComissao != value))
				{
					this.OnvalorComissaoChanging(value);
					this.SendPropertyChanging();
					this._valorComissao = value;
					this.SendPropertyChanged("valorComissao");
					this.OnvalorComissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refinanciamento", DbType="Bit")]
		public System.Nullable<bool> refinanciamento
		{
			get
			{
				return this._refinanciamento;
			}
			set
			{
				if ((this._refinanciamento != value))
				{
					this.OnrefinanciamentoChanging(value);
					this.SendPropertyChanging();
					this._refinanciamento = value;
					this.SendPropertyChanged("refinanciamento");
					this.OnrefinanciamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banco", DbType="NVarChar(50)")]
		public string banco
		{
			get
			{
				return this._banco;
			}
			set
			{
				if ((this._banco != value))
				{
					this.OnbancoChanging(value);
					this.SendPropertyChanging();
					this._banco = value;
					this.SendPropertyChanged("banco");
					this.OnbancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formaPagamento", DbType="NVarChar(50)")]
		public string formaPagamento
		{
			get
			{
				return this._formaPagamento;
			}
			set
			{
				if ((this._formaPagamento != value))
				{
					this.OnformaPagamentoChanging(value);
					this.SendPropertyChanging();
					this._formaPagamento = value;
					this.SendPropertyChanged("formaPagamento");
					this.OnformaPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacao", DbType="NVarChar(500)")]
		public string observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				if ((this._observacao != value))
				{
					this.OnobservacaoChanging(value);
					this.SendPropertyChanging();
					this._observacao = value;
					this.SendPropertyChanged("observacao");
					this.OnobservacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Emprestimo_Parcela", Storage="_Parcela", ThisKey="idEmprestimo", OtherKey="idEmprestimo")]
		public EntitySet<Parcela> Parcela
		{
			get
			{
				return this._Parcela;
			}
			set
			{
				this._Parcela.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Emprestimo", Storage="_Cliente", ThisKey="idCliente", OtherKey="idCliente", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Emprestimo.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Emprestimo.Add(this);
						this._idCliente = value.idCliente;
					}
					else
					{
						this._idCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Parcela(Parcela entity)
		{
			this.SendPropertyChanging();
			entity.Emprestimo = this;
		}
		
		private void detach_Parcela(Parcela entity)
		{
			this.SendPropertyChanging();
			entity.Emprestimo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FPagamento")]
	public partial class FPagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPagamento;
		
		private string _nomePagamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPagamentoChanging(int value);
    partial void OnidPagamentoChanged();
    partial void OnnomePagamentoChanging(string value);
    partial void OnnomePagamentoChanged();
    #endregion
		
		public FPagamento()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPagamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPagamento
		{
			get
			{
				return this._idPagamento;
			}
			set
			{
				if ((this._idPagamento != value))
				{
					this.OnidPagamentoChanging(value);
					this.SendPropertyChanging();
					this._idPagamento = value;
					this.SendPropertyChanged("idPagamento");
					this.OnidPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomePagamento", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomePagamento
		{
			get
			{
				return this._nomePagamento;
			}
			set
			{
				if ((this._nomePagamento != value))
				{
					this.OnnomePagamentoChanging(value);
					this.SendPropertyChanging();
					this._nomePagamento = value;
					this.SendPropertyChanged("nomePagamento");
					this.OnnomePagamentoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AplicacaoCliente")]
	public partial class View_AplicacaoCliente
	{
		
		private int _idCliente;
		
		private System.Nullable<bool> _statusEmprestimo;
		
		private string _codCliente;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private decimal _valor;
		
		private short _taxa;
		
		private decimal _valorTotal;
		
		private short _qtdParcela;
		
		private decimal _valorParcela;
		
		private System.DateTime _vencimento;
		
		private System.Nullable<bool> _refinanciamento;
		
		private System.Nullable<decimal> _complemento;
		
		private string _observacao;
		
		public View_AplicacaoCliente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusEmprestimo", DbType="Bit")]
		public System.Nullable<bool> statusEmprestimo
		{
			get
			{
				return this._statusEmprestimo;
			}
			set
			{
				if ((this._statusEmprestimo != value))
				{
					this._statusEmprestimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this._codCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="Date")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this._dataCadastro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(18,0) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this._valor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxa", DbType="SmallInt NOT NULL")]
		public short taxa
		{
			get
			{
				return this._taxa;
			}
			set
			{
				if ((this._taxa != value))
				{
					this._taxa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorTotal", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorTotal
		{
			get
			{
				return this._valorTotal;
			}
			set
			{
				if ((this._valorTotal != value))
				{
					this._valorTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdParcela", DbType="SmallInt NOT NULL")]
		public short qtdParcela
		{
			get
			{
				return this._qtdParcela;
			}
			set
			{
				if ((this._qtdParcela != value))
				{
					this._qtdParcela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorParcela", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorParcela
		{
			get
			{
				return this._valorParcela;
			}
			set
			{
				if ((this._valorParcela != value))
				{
					this._valorParcela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimento", DbType="Date NOT NULL")]
		public System.DateTime vencimento
		{
			get
			{
				return this._vencimento;
			}
			set
			{
				if ((this._vencimento != value))
				{
					this._vencimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refinanciamento", DbType="Bit")]
		public System.Nullable<bool> refinanciamento
		{
			get
			{
				return this._refinanciamento;
			}
			set
			{
				if ((this._refinanciamento != value))
				{
					this._refinanciamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this._complemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacao", DbType="NVarChar(500)")]
		public string observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				if ((this._observacao != value))
				{
					this._observacao = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Refinanciar")]
	public partial class View_Refinanciar
	{
		
		private int _idCliente;
		
		private string _codCliente;
		
		private System.DateTime _vencimento;
		
		private string _nomeCliente;
		
		private string _telCelularzap;
		
		private decimal _valorParcela;
		
		private System.Nullable<decimal> _complemento;
		
		public View_Refinanciar()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this._codCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimento", DbType="Date NOT NULL")]
		public System.DateTime vencimento
		{
			get
			{
				return this._vencimento;
			}
			set
			{
				if ((this._vencimento != value))
				{
					this._vencimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCliente", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomeCliente
		{
			get
			{
				return this._nomeCliente;
			}
			set
			{
				if ((this._nomeCliente != value))
				{
					this._nomeCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telCelularzap", DbType="NVarChar(20)")]
		public string telCelularzap
		{
			get
			{
				return this._telCelularzap;
			}
			set
			{
				if ((this._telCelularzap != value))
				{
					this._telCelularzap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorParcela", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorParcela
		{
			get
			{
				return this._valorParcela;
			}
			set
			{
				if ((this._valorParcela != value))
				{
					this._valorParcela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this._complemento = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_ClienteEmprestimo")]
	public partial class View_ClienteEmprestimo
	{
		
		private int _idEmprestimo;
		
		private string _codCliente;
		
		private System.Nullable<bool> _statusEmprestimo;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private decimal _valor;
		
		private short _taxa;
		
		private decimal _valorTotal;
		
		private string _nomeAtendente;
		
		private System.Nullable<int> _percentComissao;
		
		private System.Nullable<decimal> _valorComissao;
		
		private string _banco;
		
		private string _formaPagamento;
		
		private System.Nullable<bool> _refinanciamento;
		
		private System.Nullable<decimal> _complemento;
		
		private string _observacao;
		
		public View_ClienteEmprestimo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmprestimo", DbType="Int NOT NULL")]
		public int idEmprestimo
		{
			get
			{
				return this._idEmprestimo;
			}
			set
			{
				if ((this._idEmprestimo != value))
				{
					this._idEmprestimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this._codCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statusEmprestimo", DbType="Bit")]
		public System.Nullable<bool> statusEmprestimo
		{
			get
			{
				return this._statusEmprestimo;
			}
			set
			{
				if ((this._statusEmprestimo != value))
				{
					this._statusEmprestimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="Date")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this._dataCadastro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Money NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this._valor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taxa", DbType="SmallInt NOT NULL")]
		public short taxa
		{
			get
			{
				return this._taxa;
			}
			set
			{
				if ((this._taxa != value))
				{
					this._taxa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorTotal", DbType="Money NOT NULL")]
		public decimal valorTotal
		{
			get
			{
				return this._valorTotal;
			}
			set
			{
				if ((this._valorTotal != value))
				{
					this._valorTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeAtendente", DbType="NVarChar(60)")]
		public string nomeAtendente
		{
			get
			{
				return this._nomeAtendente;
			}
			set
			{
				if ((this._nomeAtendente != value))
				{
					this._nomeAtendente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentComissao", DbType="Int")]
		public System.Nullable<int> percentComissao
		{
			get
			{
				return this._percentComissao;
			}
			set
			{
				if ((this._percentComissao != value))
				{
					this._percentComissao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorComissao", DbType="Money")]
		public System.Nullable<decimal> valorComissao
		{
			get
			{
				return this._valorComissao;
			}
			set
			{
				if ((this._valorComissao != value))
				{
					this._valorComissao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banco", DbType="NVarChar(50)")]
		public string banco
		{
			get
			{
				return this._banco;
			}
			set
			{
				if ((this._banco != value))
				{
					this._banco = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formaPagamento", DbType="NVarChar(50)")]
		public string formaPagamento
		{
			get
			{
				return this._formaPagamento;
			}
			set
			{
				if ((this._formaPagamento != value))
				{
					this._formaPagamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refinanciamento", DbType="Bit")]
		public System.Nullable<bool> refinanciamento
		{
			get
			{
				return this._refinanciamento;
			}
			set
			{
				if ((this._refinanciamento != value))
				{
					this._refinanciamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="Money")]
		public System.Nullable<decimal> complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this._complemento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacao", DbType="NVarChar(500)")]
		public string observacao
		{
			get
			{
				return this._observacao;
			}
			set
			{
				if ((this._observacao != value))
				{
					this._observacao = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Recebimento")]
	public partial class View_Recebimento
	{
		
		private int _idCliente;
		
		private string _codCliente;
		
		private string _nomeCliente;
		
		private System.DateTime _vencimento;
		
		private decimal _valorParcela;
		
		private bool _paga;
		
		public View_Recebimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCliente", DbType="Int NOT NULL")]
		public int idCliente
		{
			get
			{
				return this._idCliente;
			}
			set
			{
				if ((this._idCliente != value))
				{
					this._idCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this._codCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomeCliente", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string nomeCliente
		{
			get
			{
				return this._nomeCliente;
			}
			set
			{
				if ((this._nomeCliente != value))
				{
					this._nomeCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vencimento", DbType="Date NOT NULL")]
		public System.DateTime vencimento
		{
			get
			{
				return this._vencimento;
			}
			set
			{
				if ((this._vencimento != value))
				{
					this._vencimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorParcela", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorParcela
		{
			get
			{
				return this._valorParcela;
			}
			set
			{
				if ((this._valorParcela != value))
				{
					this._valorParcela = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paga", DbType="Bit NOT NULL")]
		public bool paga
		{
			get
			{
				return this._paga;
			}
			set
			{
				if ((this._paga != value))
				{
					this._paga = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
